op_meeting_notifier:
    from:           openproject@mysite.com
    reply:          noreply@mysite.com
    subject_prefix: '[OP] '
    date_format:    'd/m/Y H:i'
env:
    prod: true
doctrine:
    dbal:
        driver:     pdo_mysql
        user:       user
        password:   password
        dbname:     openproject
